name: Publish VSIX

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Package and publish
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
        run: |
          npx vsce package -o package.vsix
          npx vsce publish --pat $VSCE_TOKEN
